### ISSUE TITLE
Many to Many relationships not working correctly when schema: false is set

### ISSUE THREAD

**Issue by particlebanana** [balderdashy/sails-mongo#254] opened 2015-03-30 03:17 UTC
Many to Many relationships create arrays of pk's in the collections when `schema: false` is set instead of writing to the join table that is created by waterline schema.

**Comment by particlebanana** [comment] 2015-03-30 03:22
This is broken in all association it seems.

**Comment by anasyb** [comment] 2015-03-30 03:57
> ... instead of writing to the join table that is created by waterline schema.

Just a clarification for whomever is picking on this issue, its not *instead* as its actually doing both.

**Comment by anasyb** [comment] 2015-03-30 16:44
Confirmed setting ```schema: true``` in ```config/models.js``` fixes it up temporary, though one of the reasons am on mangodb is to have ```schema: false```... so I hope this gets fixed soon!

**Comment by devinivy** [comment] 2015-04-04 19:04
@particlebanana what should the adapters expect from waterline (in `values` arguments) in fields which are associations?  Will waterline pass objects/arrays there, or would those be stripped-out?

**Comment by anasyb** [comment] 2015-04-18 00:06
very interesting question... maybe its waterline to blame for this issue not the adapter. @mgenev maybe you should wait for an answer before attempting to resolve this... especially if its waterline asking the adapter to init those fields named after associations.

**Comment by mgenev** [comment] 2015-04-18 01:34
yeah, i've been under the impression that it's on the waterline side...

**Comment by devinivy** [comment] 2015-04-18 16:26
I think it might be as well.  @dmarcelino didn't you find that `schema: false` changed how waterline sent the adapters association data?

**Comment by devinivy** [comment] 2015-04-18 16:47
I have a hunch!  The schema for a collection appears to _not_ include attributes for collections ([see here](https://github.com/balderdashy/waterline/blob/713d9677dec0e0a252028eab67e8007b665b07be/lib/waterline/core/schema.js#L55-L59)).  That makes enough sense, I think.  However, the way that a model's values are cleaned by the schema doesn't take into account the possible existence of collections attributes when `schema: false` ([see here](https://github.com/balderdashy/waterline/blob/713d9677dec0e0a252028eab67e8007b665b07be/lib/waterline/core/schema.js#L194-L205)).  That causes this inconsistency.

@particlebanana is there some good reason that adapters should deal with this case?  It seems to me as though waterline should indeed _always_ strip out collection attributes when cleaning values to send to an adapter, but maybe there's more to it!

**Comment by dmarcelino** [comment] 2015-04-18 18:33
@devinivy, that was mentioned in https://github.com/balderdashy/waterline/issues/429#issuecomment-76535199. I think there is a bug in waterline core because `.update()` and `.create()` should be *atomic* and should not include association data. In other words associations need to be stripped before being passed to the adapter.

**Comment by dmarcelino** [comment] 2015-04-19 18:47
@devinivy, I've just tried commenting out [schema.js#L198](https://github.com/balderdashy/waterline/blob/713d9677dec0e0a252028eab67e8007b665b07be/lib/waterline/core/schema.js#L198):
``` javascript
if(!this.hasSchema) return values;
```

And it makes all sails-orientdb tests pass when `schema: 'false'` which is a big improvement! So I think you're onto something! :wink:

**Comment by devinivy** [comment] 2015-04-19 19:30
Nice– now this seems pretty clearly to be a problem in waterline, so I think we ought to move this conversation over to https://github.com/balderdashy/waterline/issues/429 .

**Comment by anasyb** [comment] 2015-04-19 19:46
Wow this issue is really a naughty kid! It started in waterline as https://github.com/balderdashy/waterline/issues/912 then jumped to sails mongo here, and now its bouncing back to another waterline issue https://github.com/balderdashy/waterline/issues/429

So if I understand correctly the issue source is pinpointed now at the fact that waterline isn't stripping out any attributes when `schema: false`, but in fact it should do some processing there particularly for associations.

Time to close this one I guess...

**Comment by devinivy** [comment] 2015-04-20 15:07
PR https://github.com/balderdashy/waterline/pull/959 posted, so feel free to test 'er out!

**Comment by devinivy** [comment] 2015-04-23 21:04
https://github.com/balderdashy/waterline/pull/959 merged.  Look for the fix in the next patch update to waterline.

**Comment by mgenev** [comment] 2015-04-26 20:38
@anasyb has tested and verified, so I'm closing

**Closed by mgenev** 2015-04-26 20:38 UTC
